// ============================================================
// 灵枢 Knowledge OS — Mock Data
// ============================================================

import type {
  SourceDocument,
  DocumentChunk,
  KnowledgeUnit,
  KnowledgeRelation,
  Expert,
  Conversation,
  Message,
  Feedback,
} from './types'

// ---- Source Documents ----
export const mockDocuments: SourceDocument[] = [
  {
    id: 'doc-1',
    title: 'Building LLM Agents — A Comprehensive Guide',
    sourceType: 'pdf',
    author: 'Lilian Weng',
    uploadedBy: 'user-1',
    workspaceId: 'ws-1',
    status: 'processed',
    createdAt: '2026-06-01T08:00:00Z',
    updatedAt: '2026-06-01T08:30:00Z',
  },
  {
    id: 'doc-2',
    title: '知识图谱构建方法论',
    sourceType: 'pdf',
    author: '丁磊',
    uploadedBy: 'user-1',
    workspaceId: 'ws-1',
    status: 'processed',
    createdAt: '2026-05-28T10:00:00Z',
    updatedAt: '2026-05-28T10:45:00Z',
  },
  {
    id: 'doc-3',
    title: 'SECI 模型在企业知识管理中的应用',
    sourceType: 'web',
    author: '野中郁次郎',
    uploadedBy: 'user-1',
    workspaceId: 'ws-1',
    status: 'processed',
    createdAt: '2026-05-25T14:00:00Z',
    updatedAt: '2026-05-25T14:20:00Z',
  },
  {
    id: 'doc-4',
    title: 'ChatGPT 在产品管理中的实践',
    sourceType: 'markdown',
    author: '产品团队',
    uploadedBy: 'user-1',
    workspaceId: 'ws-1',
    status: 'parsed',
    createdAt: '2026-06-05T09:00:00Z',
    updatedAt: '2026-06-05T09:15:00Z',
  },
  {
    id: 'doc-5',
    title: 'Design Thinking & AI: 从用户研究到产品设计',
    sourceType: 'pdf',
    author: 'IDEO Research',
    uploadedBy: 'user-1',
    workspaceId: 'ws-1',
    status: 'processed',
    createdAt: '2026-05-20T11:00:00Z',
    updatedAt: '2026-05-20T11:40:00Z',
  },
  {
    id: 'doc-6',
    title: '专访：姚期智谈量子计算与人工智能交叉',
    sourceType: 'interview',
    author: '科技评论',
    uploadedBy: 'user-1',
    workspaceId: 'ws-1',
    status: 'processed',
    createdAt: '2026-06-03T16:00:00Z',
    updatedAt: '2026-06-03T16:25:00Z',
  },
  {
    id: 'doc-7',
    title: '从零构建 RAG 系统的 12 个工程陷阱',
    sourceType: 'web',
    author: 'Jason Liu',
    uploadedBy: 'user-1',
    workspaceId: 'ws-1',
    status: 'processed',
    createdAt: '2026-06-07T07:30:00Z',
    updatedAt: '2026-06-07T07:55:00Z',
  },
  {
    id: 'doc-8',
    title: '互联网产品经理能力模型 v3.0',
    sourceType: 'markdown',
    author: '产品学院',
    uploadedBy: 'user-1',
    workspaceId: 'ws-1',
    status: 'uploaded',
    createdAt: '2026-06-08T10:00:00Z',
    updatedAt: '2026-06-08T10:00:00Z',
  },
]

// ---- Document Chunks ----
export const mockChunks: DocumentChunk[] = [
  {
    id: 'chunk-1-1',
    documentId: 'doc-1',
    chunkIndex: 0,
    content:
      'LLM Agent 的核心架构包括：规划模块（Planning）、记忆模块（Memory）、工具使用（Tool Use）。规划模块负责将复杂任务分解为可执行的子任务...',
    summary: 'LLM Agent 的核心架构三大模块',
    createdAt: '2026-06-01T08:30:00Z',
  },
  {
    id: 'chunk-1-2',
    documentId: 'doc-1',
    chunkIndex: 1,
    content:
      '长期记忆是 Agent 系统的关键挑战。与短期工作记忆不同，长期记忆需要持久化存储、高效检索和上下文压缩。常见的方案包括向量数据库 + 结构化知识图谱的混合检索...',
    summary: 'Agent 长期记忆的挑战与方案',
    createdAt: '2026-06-01T08:30:00Z',
  },
  {
    id: 'chunk-2-1',
    documentId: 'doc-2',
    chunkIndex: 0,
    content:
      '知识图谱的构建分为自顶向下和自底向上两种方法论。自顶向下从本体设计开始，定义实体和关系类型；自底向上从数据中自动抽取实体和关系...',
    summary: '知识图谱构建的两种方法论',
    createdAt: '2026-05-28T10:45:00Z',
  },
  {
    id: 'chunk-3-1',
    documentId: 'doc-3',
    chunkIndex: 0,
    content:
      'SECI 模型将知识创造过程分为四个阶段：社会化（Socialization）、外化（Externalization）、组合化（Combination）、内化（Internalization）。这四个阶段形成一个持续的知识螺旋...',
    summary: 'SECI 模型的四个阶段',
    createdAt: '2026-05-25T14:20:00Z',
  },
]

// ---- Knowledge Units ----
export const mockKnowledgeUnits: KnowledgeUnit[] = [
  {
    id: 'ku-1',
    name: 'LLM Agent 架构',
    type: 'concept',
    description:
      'LLM Agent 是一种以大语言模型为核心推理引擎的智能体系统，通过规划、记忆和工具使用三大模块协同工作，能够自主完成复杂的认知任务。',
    summary: '以大语言模型为核心的智能体系统架构',
    keywords: ['LLM', 'Agent', '规划', '记忆', '工具使用'],
    tags: ['AI', 'Agent', '架构'],
    confidence: 0.95,
    status: 'approved',
    seciStage: 'combination',
    sourceDocumentIds: ['doc-1'],
    sourceChunkIds: ['chunk-1-1'],
    createdBy: 'system',
    reviewedBy: 'user-1',
    workspaceId: 'ws-1',
    usageCount: 156,
    createdAt: '2026-06-01T09:00:00Z',
    updatedAt: '2026-06-01T09:00:00Z',
  },
  {
    id: 'ku-2',
    name: 'Agent 长期记忆',
    type: 'concept',
    description:
      'Agent 长期记忆是 Agent 系统中用于持久化存储历史交互、知识和经验的能力。区别于短期工作记忆，长期记忆需要解决存储、检索、压缩、更新和遗忘五个核心问题。',
    summary: '持久化知识存储与检索系统',
    keywords: ['长期记忆', '向量数据库', '知识图谱', '上下文压缩'],
    tags: ['AI', 'Agent', '记忆'],
    confidence: 0.9,
    status: 'approved',
    seciStage: 'externalization',
    sourceDocumentIds: ['doc-1'],
    sourceChunkIds: ['chunk-1-2'],
    createdBy: 'system',
    reviewedBy: 'user-1',
    workspaceId: 'ws-1',
    usageCount: 132,
    createdAt: '2026-06-01T09:30:00Z',
    updatedAt: '2026-06-01T09:30:00Z',
  },
  {
    id: 'ku-3',
    name: '知识图谱混合检索',
    type: 'methodology',
    description:
      '结合向量相似度检索和图结构遍历的混合检索方法。向量检索负责语义匹配，图谱遍历负责关系发现，两者结合可以提升知识检索的召回率和准确率。',
    summary: '向量检索 + 图谱遍历的混合检索策略',
    keywords: ['混合检索', '向量数据库', '图谱遍历', 'RAG'],
    tags: ['检索', '知识图谱', 'RAG'],
    confidence: 0.88,
    status: 'approved',
    seciStage: 'combination',
    sourceDocumentIds: ['doc-1', 'doc-2'],
    sourceChunkIds: ['chunk-1-2', 'chunk-2-1'],
    createdBy: 'system',
    workspaceId: 'ws-1',
    usageCount: 98,
    createdAt: '2026-06-02T10:00:00Z',
    updatedAt: '2026-06-02T10:00:00Z',
  },
  {
    id: 'ku-4',
    name: 'SECI 知识螺旋',
    type: 'methodology',
    description:
      '由野中郁次郎提出的组织知识创造理论，将隐性知识和显性知识的转化分为社会化、外化、组合化、内化四个阶段，形成持续的知识创造螺旋。',
    summary: '组织知识创造的四个阶段模型',
    keywords: ['SECI', '知识管理', '隐性知识', '显性知识', '组织学习'],
    tags: ['知识管理', '方法论', '组织'],
    confidence: 0.97,
    status: 'approved',
    seciStage: 'externalization',
    sourceDocumentIds: ['doc-3'],
    sourceChunkIds: ['chunk-3-1'],
    createdBy: 'system',
    reviewedBy: 'user-1',
    workspaceId: 'ws-1',
    usageCount: 210,
    createdAt: '2026-05-25T15:00:00Z',
    updatedAt: '2026-05-25T15:00:00Z',
  },
  {
    id: 'ku-5',
    name: 'RAG 系统工程实践',
    type: 'case_experience',
    description:
      '从零构建 RAG 系统过程中遇到的 12 个工程陷阱，包括：分块策略不当、检索不准确、上下文窗口管理、提示词设计、幻觉控制、评估体系缺失等。每个陷阱都包含具体场景和解决方案。',
    summary: '构建 RAG 系统的实战经验总结',
    keywords: ['RAG', '工程实践', '陷阱', '检索增强生成'],
    tags: ['RAG', '工程', '经验'],
    confidence: 0.85,
    status: 'approved',
    seciStage: 'internalization',
    sourceDocumentIds: ['doc-7'],
    sourceChunkIds: [],
    createdBy: 'user',
    workspaceId: 'ws-1',
    usageCount: 67,
    createdAt: '2026-06-07T08:00:00Z',
    updatedAt: '2026-06-07T08:00:00Z',
  },
  {
    id: 'ku-6',
    name: '产品经理',
    type: 'industry_profession',
    description:
      '产品经理是负责定义产品愿景、战略和功能优先级的关键角色。需要具备用户研究、市场分析、数据决策和跨团队协作能力。在 AI 时代，产品经理还需要理解 AI 能力边界和数据闭环。',
    summary: '负责产品策略和功能定义的核心角色',
    keywords: ['产品经理', 'PM', '用户研究', '需求分析', '产品策略'],
    tags: ['职业', '产品'],
    confidence: 0.9,
    status: 'approved',
    seciStage: 'combination',
    sourceDocumentIds: ['doc-4', 'doc-8'],
    sourceChunkIds: [],
    createdBy: 'system',
    workspaceId: 'ws-1',
    usageCount: 185,
    createdAt: '2026-06-05T10:00:00Z',
    updatedAt: '2026-06-05T10:00:00Z',
  },
  {
    id: 'ku-7',
    name: 'Design Thinking',
    type: 'methodology',
    description:
      '以人为中心的设计思维方法论，包含共情、定义、构思、原型和测试五个阶段。在 AI 产品设计中，Design Thinking 帮助团队在技术可行性和用户需求之间找到平衡。',
    summary: '以人为中心的设计思维五阶段方法论',
    keywords: ['Design Thinking', '设计思维', '用户中心', '原型', '创新'],
    tags: ['设计', '方法论', '创新'],
    confidence: 0.92,
    status: 'approved',
    seciStage: 'externalization',
    sourceDocumentIds: ['doc-5'],
    sourceChunkIds: [],
    createdBy: 'system',
    workspaceId: 'ws-1',
    usageCount: 143,
    createdAt: '2026-05-20T12:00:00Z',
    updatedAt: '2026-05-20T12:00:00Z',
  },
  {
    id: 'ku-8',
    name: '量子计算与 AI',
    type: 'concept',
    description:
      '量子计算利用量子比特的叠加和纠缠特性，在某些计算任务上具有超越经典计算机的潜力。在 AI 领域，量子计算可能对优化问题、采样问题和某些机器学习算法带来质的提升。',
    summary: '量子计算在人工智能领域的应用前景',
    keywords: ['量子计算', '人工智能', '量子比特', '优化'],
    tags: ['AI', '量子计算', '前沿'],
    confidence: 0.75,
    status: 'candidate',
    seciStage: 'socialization',
    sourceDocumentIds: ['doc-6'],
    sourceChunkIds: [],
    createdBy: 'system',
    workspaceId: 'ws-1',
    usageCount: 23,
    createdAt: '2026-06-03T17:00:00Z',
    updatedAt: '2026-06-03T17:00:00Z',
  },
  {
    id: 'ku-9',
    name: '提示词工程',
    type: 'methodology',
    description:
      '提示词工程是设计和优化 LLM 输入提示的系统方法论，包括 few-shot、chain-of-thought、tree-of-thought、角色设定、格式约束等技巧。好的提示词设计能显著提升模型输出质量。',
    summary: '设计和优化 LLM 提示的系统方法',
    keywords: ['提示词工程', 'Prompt', 'Few-shot', 'Chain-of-Thought'],
    tags: ['AI', 'Prompt', '方法论'],
    confidence: 0.9,
    status: 'approved',
    seciStage: 'combination',
    sourceDocumentIds: ['doc-1'],
    sourceChunkIds: [],
    createdBy: 'system',
    workspaceId: 'ws-1',
    usageCount: 178,
    createdAt: '2026-06-02T14:00:00Z',
    updatedAt: '2026-06-02T14:00:00Z',
  },
  {
    id: 'ku-10',
    name: 'AI 产品设计策略',
    type: 'case_experience',
    description:
      '在多个 AI 产品从 0 到 1 的过程中总结的设计策略：先定义 AI 能做什么（能力边界），再定义用户需要什么（需求边界），在交集处设计产品。避免过度承诺 AI 能力，设计优雅的降级和人工兜底方案。',
    summary: 'AI 产品从 0 到 1 的设计策略总结',
    keywords: ['AI 产品', '设计策略', '能力边界', '降级方案'],
    tags: ['AI', '产品设计', '经验'],
    confidence: 0.82,
    status: 'candidate',
    seciStage: 'internalization',
    sourceDocumentIds: ['doc-4', 'doc-5'],
    sourceChunkIds: [],
    createdBy: 'user',
    workspaceId: 'ws-1',
    usageCount: 45,
    createdAt: '2026-06-06T11:00:00Z',
    updatedAt: '2026-06-06T11:00:00Z',
  },
  {
    id: 'ku-11',
    name: '上下文窗口管理',
    type: 'concept',
    description:
      'LLM 的上下文窗口是有限的，如何高效管理上下文是 Agent 设计的关键。常见策略包括：滑动窗口、摘要压缩、分层记忆、选择性遗忘。上下文窗口管理直接影响 Agent 的长期任务执行能力。',
    summary: 'LLM 上下文窗口的高效管理策略',
    keywords: ['上下文窗口', 'Token', '压缩', 'Agent'],
    tags: ['AI', 'Agent', '上下文'],
    confidence: 0.88,
    status: 'approved',
    seciStage: 'externalization',
    sourceDocumentIds: ['doc-1'],
    sourceChunkIds: ['chunk-1-2'],
    createdBy: 'system',
    workspaceId: 'ws-1',
    usageCount: 112,
    createdAt: '2026-06-01T10:00:00Z',
    updatedAt: '2026-06-01T10:00:00Z',
  },
  {
    id: 'ku-12',
    name: '知识孤岛',
    type: 'concept',
    description:
      '在知识图谱中，缺乏与其他节点连接的知识单元称为知识孤岛。知识孤岛反映了知识未被关联和整合的状态，是知识管理系统需要识别和处理的问题。',
    summary: '知识图谱中孤立未连接的知识节点',
    keywords: ['知识孤岛', '图谱', '知识管理'],
    tags: ['知识管理', '图谱'],
    confidence: 0.8,
    status: 'candidate',
    seciStage: 'externalization',
    sourceDocumentIds: ['doc-2'],
    sourceChunkIds: [],
    createdBy: 'system',
    workspaceId: 'ws-1',
    usageCount: 15,
    createdAt: '2026-06-04T08:00:00Z',
    updatedAt: '2026-06-04T08:00:00Z',
  },
]

// ---- Knowledge Relations ----
export const mockRelations: KnowledgeRelation[] = [
  {
    id: 'rel-1',
    sourceUnitId: 'ku-1',
    targetUnitId: 'ku-2',
    relationType: 'combined_into',
    description: 'Agent 架构使用长期记忆作为核心模块',
    evidenceChunkIds: ['chunk-1-1'],
    confidence: 0.95,
    status: 'approved',
    createdBy: 'system',
    createdAt: '2026-06-01T09:00:00Z',
    updatedAt: '2026-06-01T09:00:00Z',
  },
  {
    id: 'rel-2',
    sourceUnitId: 'ku-2',
    targetUnitId: 'ku-3',
    relationType: 'applied_in',
    description: '长期记忆采用混合检索方法实现',
    evidenceChunkIds: ['chunk-1-2', 'chunk-2-1'],
    confidence: 0.9,
    status: 'approved',
    createdBy: 'system',
    createdAt: '2026-06-02T10:00:00Z',
    updatedAt: '2026-06-02T10:00:00Z',
  },
  {
    id: 'rel-3',
    sourceUnitId: 'ku-3',
    targetUnitId: 'ku-5',
    relationType: 'validated_by',
    description: 'RAG 工程实践验证混合检索有效性',
    evidenceChunkIds: [],
    confidence: 0.82,
    status: 'approved',
    createdBy: 'user',
    createdAt: '2026-06-07T08:00:00Z',
    updatedAt: '2026-06-07T08:00:00Z',
  },
  {
    id: 'rel-4',
    sourceUnitId: 'ku-4',
    targetUnitId: 'ku-5',
    relationType: 'applied_in',
    description: 'SECI 模型在 RAG 系统建设中应用',
    evidenceChunkIds: [],
    confidence: 0.75,
    status: 'candidate',
    createdBy: 'system',
    createdAt: '2026-06-07T08:30:00Z',
    updatedAt: '2026-06-07T08:30:00Z',
  },
  {
    id: 'rel-5',
    sourceUnitId: 'ku-1',
    targetUnitId: 'ku-9',
    relationType: 'supports',
    description: '提示词工程支持 Agent 的规划模块',
    evidenceChunkIds: [],
    confidence: 0.88,
    status: 'approved',
    createdBy: 'system',
    createdAt: '2026-06-02T14:00:00Z',
    updatedAt: '2026-06-02T14:00:00Z',
  },
  {
    id: 'rel-6',
    sourceUnitId: 'ku-7',
    targetUnitId: 'ku-10',
    relationType: 'applied_in',
    description: 'Design Thinking 方法论应用于 AI 产品设计',
    evidenceChunkIds: [],
    confidence: 0.85,
    status: 'approved',
    createdBy: 'system',
    createdAt: '2026-06-06T11:00:00Z',
    updatedAt: '2026-06-06T11:00:00Z',
  },
  {
    id: 'rel-7',
    sourceUnitId: 'ku-6',
    targetUnitId: 'ku-10',
    relationType: 'relates_to',
    description: '产品经理是 AI 产品设计策略的主要实践者',
    evidenceChunkIds: [],
    confidence: 0.8,
    status: 'approved',
    createdBy: 'system',
    createdAt: '2026-06-06T11:30:00Z',
    updatedAt: '2026-06-06T11:30:00Z',
  },
  {
    id: 'rel-8',
    sourceUnitId: 'ku-1',
    targetUnitId: 'ku-11',
    relationType: 'combined_into',
    description: 'Agent 架构需要上下文窗口管理能力',
    evidenceChunkIds: ['chunk-1-2'],
    confidence: 0.9,
    status: 'approved',
    createdBy: 'system',
    createdAt: '2026-06-01T10:00:00Z',
    updatedAt: '2026-06-01T10:00:00Z',
  },
  {
    id: 'rel-9',
    sourceUnitId: 'ku-2',
    targetUnitId: 'ku-11',
    relationType: 'complements',
    description: '长期记忆与上下文窗口管理互补',
    evidenceChunkIds: ['chunk-1-2'],
    confidence: 0.87,
    status: 'approved',
    createdBy: 'system',
    createdAt: '2026-06-01T10:30:00Z',
    updatedAt: '2026-06-01T10:30:00Z',
  },
  {
    id: 'rel-10',
    sourceUnitId: 'ku-4',
    targetUnitId: 'ku-7',
    relationType: 'relates_to',
    description: 'SECI 和 Design Thinking 都关注知识的转化过程',
    evidenceChunkIds: [],
    confidence: 0.7,
    status: 'candidate',
    createdBy: 'system',
    createdAt: '2026-06-05T12:00:00Z',
    updatedAt: '2026-06-05T12:00:00Z',
  },
  {
    id: 'rel-11',
    sourceUnitId: 'ku-6',
    targetUnitId: 'ku-7',
    relationType: 'relates_to',
    description: '产品经理常用 Design Thinking 方法论',
    evidenceChunkIds: [],
    confidence: 0.78,
    status: 'candidate',
    createdBy: 'system',
    createdAt: '2026-06-05T12:30:00Z',
    updatedAt: '2026-06-05T12:30:00Z',
  },
  {
    id: 'rel-12',
    sourceUnitId: 'ku-5',
    targetUnitId: 'ku-12',
    relationType: 'contradicts',
    description: 'RAG 实践表明孤岛知识难以被检索利用',
    evidenceChunkIds: [],
    confidence: 0.65,
    status: 'candidate',
    createdBy: 'system',
    createdAt: '2026-06-07T09:00:00Z',
    updatedAt: '2026-06-07T09:00:00Z',
  },
]

// ---- Experts ----
export const mockExperts: Expert[] = [
  {
    id: 'exp-1',
    name: '姚期智',
    title: '计算机科学家 · 图灵奖得主',
    domain: ['计算机科学', '量子计算', '人工智能'],
    description:
      '世界著名计算机科学家，2000 年图灵奖得主，在计算理论、密码学和量子计算领域有开创性贡献。近年来关注量子计算与人工智能的交叉领域。',
    sourceDocumentIds: ['doc-6'],
    styleProfile: '严谨、理论导向、擅长从第一性原理出发',
    knowledgeUnitIds: ['ku-8'],
    status: 'active',
    workspaceId: 'ws-1',
    createdAt: '2026-06-03T17:00:00Z',
    updatedAt: '2026-06-03T17:00:00Z',
  },
  {
    id: 'exp-2',
    name: 'Lilian Weng',
    title: 'OpenAI 安全系统负责人',
    domain: ['AI 安全', 'LLM Agent', '强化学习'],
    description:
      'OpenAI 安全系统团队负责人，以撰写高质量 AI 技术博客著称。她的博客文章是 LLM Agent 领域的重要参考文献。',
    sourceDocumentIds: ['doc-1'],
    styleProfile: '清晰、技术导向、体系化',
    knowledgeUnitIds: ['ku-1', 'ku-2', 'ku-9', 'ku-11'],
    status: 'active',
    workspaceId: 'ws-1',
    createdAt: '2026-06-01T09:00:00Z',
    updatedAt: '2026-06-01T09:00:00Z',
  },
  {
    id: 'exp-3',
    name: '野中郁次郎',
    title: '知识管理理论之父',
    domain: ['知识管理', '组织学习', '创新'],
    description:
      '一桥大学名誉教授，SECI 模型的提出者。其知识创造理论深刻影响了全球企业的知识管理实践。',
    sourceDocumentIds: ['doc-3'],
    styleProfile: '系统性、哲学思辨、案例驱动',
    knowledgeUnitIds: ['ku-4'],
    status: 'active',
    workspaceId: 'ws-1',
    createdAt: '2026-05-25T15:00:00Z',
    updatedAt: '2026-05-25T15:00:00Z',
  },
]

// ---- Conversations & Messages ----
export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    title: 'Agent 长期记忆设计方案讨论',
    mode: 'normal',
    workspaceId: 'ws-1',
    userId: 'user-1',
    createdAt: '2026-06-07T14:00:00Z',
    updatedAt: '2026-06-07T14:30:00Z',
  },
  {
    id: 'conv-2',
    title: '与姚期智探讨量子计算',
    mode: 'expert',
    expertIds: ['exp-1'],
    workspaceId: 'ws-1',
    userId: 'user-1',
    createdAt: '2026-06-06T10:00:00Z',
    updatedAt: '2026-06-06T10:45:00Z',
  },
]

export const mockMessages: Record<string, Message[]> = {
  'conv-1': [
    {
      id: 'msg-1-1',
      conversationId: 'conv-1',
      role: 'user',
      content: 'Agent 的长期记忆应该如何设计？有哪些关键的工程决策？',
      createdAt: '2026-06-07T14:00:00Z',
    },
    {
      id: 'msg-1-2',
      conversationId: 'conv-1',
      role: 'assistant',
      content:
        '设计 Agent 长期记忆需要做几个关键决策：\n\n1. **存储架构**：推荐向量数据库 + 结构化知识图谱的混合方案。向量库处理语义相似度检索，图谱维护知识间的逻辑关系。\n\n2. **记忆粒度**：建议以"知识单元"而非原始对话为最小粒度。每个知识单元包含：内容、来源、关系、置信度、时间戳。\n\n3. **检索策略**：多阶段检索 — 先用向量检索粗筛，再借助图谱的邻居关系扩展相关节点，最后使用 Reranker 精排。\n\n4. **记忆管理**：需要遗忘机制（根据使用频率和时效性降权）、去重机制（相似知识合并）、更新机制（新证据修正旧知识）。',
      citations: [
        {
          sourceDocumentId: 'doc-1',
          chunkId: 'chunk-1-2',
          text: '长期记忆需要持久化存储、高效检索和上下文压缩...',
        },
      ],
      relatedKnowledgeUnitIds: ['ku-2', 'ku-3', 'ku-11'],
      createdAt: '2026-06-07T14:00:30Z',
    },
    {
      id: 'msg-1-3',
      conversationId: 'conv-1',
      role: 'user',
      content: '混合检索中，向量检索和图谱检索的权重如何分配？',
      createdAt: '2026-06-07T14:05:00Z',
    },
    {
      id: 'msg-1-4',
      conversationId: 'conv-1',
      role: 'assistant',
      content:
        '权重分配取决于查询类型：\n\n- **事实性查询**（"什么是 X"）：向量检索权重更高（70-80%），因为需要语义匹配精确的答案片段。\n- **探索性查询**（"X 和 Y 有什么关系"）：图谱权重更高（50-60%），因为关系发现是核心需求。\n- **综合查询**：建议动态权重 — 先用向量检索获取 top-K，再沿着图谱边扩展到 K-hop 邻居，最后用 Reranker 统一排序。\n\n实际工程中，可以使用一个小型分类模型先判断查询类型，再决定权重分配策略。',
      citations: [
        {
          sourceDocumentId: 'doc-1',
          chunkId: 'chunk-2-1',
          text: '结合向量相似度检索和图结构遍历的混合检索方法...',
        },
      ],
      relatedKnowledgeUnitIds: ['ku-3', 'ku-5'],
      createdAt: '2026-06-07T14:05:45Z',
    },
  ],
  'conv-2': [
    {
      id: 'msg-2-1',
      conversationId: 'conv-2',
      role: 'user',
      content: '姚教授，量子计算对 AI 的最大影响会是什么？',
      createdAt: '2026-06-06T10:00:00Z',
    },
    {
      id: 'msg-2-2',
      conversationId: 'conv-2',
      role: 'expert',
      content:
        '量子计算对 AI 的影响需要分三个阶段来看。\n\n短期（5-10年）：量子计算主要在优化问题上发挥作用 — 如组合优化、采样问题。这些对机器学习中的超参数搜索、贝叶斯推理有直接帮助。\n\n中期（10-20年）：量子机器学习算法会逐步成熟。量子神经网络、量子核方法可能在某些任务上超越经典方法。\n\n长期：量子计算可能从根本上改变我们对"计算"的认知，就像当年晶体管改变电子学一样。但这个时间线很难预测。\n\n关键点：不是量子计算要取代经典计算，而是两者协作。量子处理特定子任务，经典计算机做整体编排。',
      citations: [
        {
          sourceDocumentId: 'doc-6',
          chunkId: 'chunk-6-0',
          text: '量子计算与人工智能的交叉领域...',
        },
      ],
      relatedKnowledgeUnitIds: ['ku-8'],
      createdAt: '2026-06-06T10:01:00Z',
    },
  ],
}

// ---- Feedback ----
export const mockFeedback: Feedback[] = [
  {
    id: 'fb-1',
    userId: 'user-1',
    targetType: 'knowledge_unit',
    targetId: 'ku-4',
    feedbackType: 'useful',
    comment: 'SECI 模型非常好地解释了知识转化的过程',
    createdAt: '2026-06-03T09:00:00Z',
  },
  {
    id: 'fb-2',
    userId: 'user-1',
    targetType: 'answer',
    targetId: 'msg-1-2',
    feedbackType: 'like',
    createdAt: '2026-06-07T14:10:00Z',
  },
  {
    id: 'fb-3',
    userId: 'user-1',
    targetType: 'knowledge_unit',
    targetId: 'ku-12',
    feedbackType: 'correction',
    comment: '知识孤岛的定义需要更精确 — 应该区分"暂时未连接"和"确实独立"两种情况',
    createdAt: '2026-06-04T10:00:00Z',
  },
]

// ---- Analytics Snapshot ----
export const mockAnalytics = {
  totalNodes: 12,
  newConceptsThisWeek: 3,
  newMethodologiesThisWeek: 2,
  newCasesThisWeek: 1,
  totalRelations: 12,
  totalUsageCount: 1210,
  totalCitationCount: 458,
  feedbackCount: 3,
  orphanNodes: 1,
  healthScore: 78,
  seciConversions: 8,
}
